---

# Endpoint providing CSV of listed companies and their tickers
asx_companies_csv: https://www.asx.com.au/asx/research/ASXListedCompanies.csv

# Endpoint providing XLS spreadsheet of all listed securities and their tickers
asx_securities_tsv: https://www.asx.com.au/programs/ISIN.xls
    # NOTE the extension is xls but the file is actuall tab separated

# Endpoint to pull individual companies data
asx_company_json: https://www.asx.com.au/asx/1/company/%s?fields=primary_share,latest_annual_reports,last_dividend,primary_share.indices
    # %s = ticker

# Endpoint to pull individual securities data
asx_single_json: https://www.asx.com.au/asx/1/share/%s # %s = ticker
  # OLD; http://data.asx.com.au/data/1/share/%s

# Endpoint to pull annoucements
asx_announcements_json: https://www.asx.com.au/asx/1/company/%s/announcements?count=20&market_sensitive=true
    # %s = ticker

# Endpoint for pulling historical ASX stock prices
floatau_historical_csv: http://float.com.au/download/%s.csv?format=stockeasy  # %s = ticker
